spring.config.import=optional:configserver:http://localhost:8888

server.port=8084

spring.application.name=payment-service

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=payment-db

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.function.definition=orderCreatedConsumer

spring.cloud.stream.bindings.orderCreatedConsumer-in-0.destination=order-created
spring.cloud.stream.bindings.orderCreatedConsumer-in-0.group=payment-service-group

spring.cloud.stream.bindings.paymentProcessed-out-0.destination=payment-processed

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest