spring.config.import=optional:configserver:http://localhost:8888

server.port=8083

spring.application.name=order-service

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=order-db

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.stream.bindings.orderCreated-out-0.destination=order-created

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest