server.port=8083

spring.mongodb.host=mongodb
spring.mongodb.port=27017
spring.mongodb.database=order-db

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true